### ISSUE TITLE
Os dados para acesso ao banco de dados estão presentes em dois lugares diferentes

### ISSUE THREAD

**Issue by orlandosaraivajr** [joicerodrigues/Prova-php2Semestre#1]
Os dados para acesso ao banco de dados estão presentes em (pelo menos) dois lugares diferentes

https://github.com/joicerodrigues/Prova-php2Semestre/blob/e1513c76ddabcad49e9a12d3341b56078e9325bd/cadastro2.php#L3

https://github.com/joicerodrigues/Prova-php2Semestre/blob/e1513c76ddabcad49e9a12d3341b56078e9325bd/dados_banco.php#L1

Qual está correto ?

**Comment by joicerodrigues** [comment]
Já fiz a correção, o correto é em:
https://github.com/joicerodrigues/Prova-php2Semestre/blob/e55c64ff9d4f1932c5aaeef3dbc952bc5f6cbdc1/create/cadastro2.php#L3
O outro arquivo já foi deletado.
